#pragma once
#define COUNT_MARKS 20
#define COUNT_COLUMNS 5
#define MAX_BALL 10
#define CHECK_SESSION 3.0f
#define NAMECOLUMN 100
#define AGECOLUMN 40
#define AVRBALLCOLUMN 100
#define UNIVERCOLUMN 100
#define IDCOLUMN 60
#define WIDTHLIST NAMECOLUMN+AGECOLUMN+AVRBALLCOLUMN+UNIVERCOLUMN+IDCOLUMN
#define HEIGHTWND 480
#define HEIGHTLIST_MAIN 330